# Generated by Django 5.2.11 on 2026-02-26 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_numero', models.CharField(help_text='Sin puntos ni guión. Ej: 12345678', max_length=8, validators=[django.core.validators.RegexValidator(message='El RUT debe tener entre 1 y 8 dígitos (sin puntos).', regex='^\\d{1,8}$')], verbose_name='RUT (número)')),
                ('rut_dv', models.CharField(help_text='0-9 o K', max_length=1, validators=[django.core.validators.RegexValidator(message='El dígito verificador debe ser 0-9 o K.', regex='^[0-9Kk]{1}$')], verbose_name='DV')),
                ('nombre_paciente', models.CharField(max_length=150, verbose_name='Nombre Paciente')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, choices=[('LAS_CONDES', 'Las Condes'), ('PROVIDENCIA', 'Providencia'), ('SANTIAGO', 'Santiago'), ('NUNOA', 'Ñuñoa'), ('VITACURA', 'Vitacura'), ('OTRA', 'Otra')], max_length=50, null=True, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('prevision', models.CharField(blank=True, choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'Particular'), ('OTRA', 'Otra')], max_length=20, null=True, verbose_name='Previsión')),
                ('nombre_mama', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Mamá')),
                ('nombre_papa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Papá')),
                ('parto', models.CharField(blank=True, choices=[('VAGINAL', 'Vaginal'), ('CESAREA', 'Cesárea'), ('INSTRUMENTAL', 'Instrumental'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Parto')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Peso (Kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Talla (cm)')),
                ('cc_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='C.C. (cm)')),
                ('apgar', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Apgar')),
                ('edad_gestacional_semanas', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)], verbose_name='Edad Gestacional (semanas)')),
                ('grupo_sanguineo_abo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True, verbose_name='Grupo Sanguíneo (ABO)')),
                ('grupo_sanguineo_rh', models.CharField(blank=True, choices=[('+', 'Rh +'), ('-', 'Rh -')], max_length=1, null=True, verbose_name='Factor Rh')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'constraints': [models.UniqueConstraint(fields=('rut_numero', 'rut_dv'), name='uq_paciente_rut')],
            },
        ),
    ]
