# Generated by Django 5.2.11 on 2026-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='comuna',
            field=models.CharField(blank=True, choices=[('RANCAGUA', 'Rancagua'), ('CODEGUA', 'Codegua'), ('COINCO', 'Coínco'), ('COLTAUCO', 'Coltauco'), ('DONIHUE', 'Doñihue'), ('GRANEROS', 'Graneros'), ('LAS_CABRAS', 'Las Cabras'), ('MACHALI', 'Machalí'), ('MALLOA', 'Malloa'), ('MOSTAZAL', 'Mostazal'), ('OLIVAR', 'Olivar'), ('PEUMO', 'Peumo'), ('PICHIDEGUA', 'Pichidegua'), ('QUINTA_DE_TILCOCO', 'Quinta de Tilcoco'), ('RENGO', 'Rengo'), ('REQUINOA', 'Requínoa'), ('SAN_VICENTE', 'San Vicente de Tagua Tagua'), ('SAN_FERNANDO', 'San Fernando'), ('CHEPICA', 'Chépica'), ('CHIMBARONGO', 'Chimbarongo'), ('LOLOL', 'Lolol'), ('NANCAGUA', 'Nancagua'), ('PALMILLA', 'Palmilla'), ('PERALILLO', 'Peralillo'), ('PLACILLA', 'Placilla'), ('PUMANQUE', 'Pumanque'), ('SANTA_CRUZ', 'Santa Cruz'), ('PICHILEMU', 'Pichilemu'), ('LA_ESTRELLA', 'La Estrella'), ('LITUECHE', 'Litueche'), ('MARCHIHUE', 'Marchihue'), ('NAVIDAD', 'Navidad'), ('PAREDONES', 'Paredones')], max_length=50, null=True, verbose_name='Comuna'),
        ),
    ]
