# Generated by Django 5.2.11 on 2026-02-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_comunas_sexta_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiere no decir')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
