# Generated by Django 5.2.11 on 2026-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_agregar_sexo_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('CHILENA', 'Chilena'), ('VENEZOLANA', 'Venezolana'), ('PERUANA', 'Peruana'), ('HAITIANA', 'Haitiana'), ('COLOMBIANA', 'Colombiana'), ('BOLIVIANA', 'Boliviana'), ('ARGENTINA', 'Argentina'), ('ECUATORIANA', 'Ecuatoriana'), ('DOMINICANA', 'Dominicana'), ('CUBANA', 'Cubana'), ('OTRA', 'Otra')], max_length=20, null=True, verbose_name='Nacionalidad'),
        ),
    ]
