# Generated by Django 5.2.11 on 2026-02-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioFUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluación')),
                ('edad_meses', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad (meses)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('perimetro_cefalico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('dpm_resultado', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('RIESGO', 'Riesgo'), ('RETRASO', 'Retraso')], max_length=20, null=True, verbose_name='Resultado DSM')),
                ('dpm_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones DSM')),
                ('lactancia_materna', models.BooleanField(default=False, verbose_name='Lactancia Materna')),
                ('alimentacion_complementaria', models.BooleanField(default=False, verbose_name='Alimentación Complementaria')),
                ('alimentacion_observaciones', models.TextField(blank=True, null=True, verbose_name='Obs. Alimentación')),
                ('vacunas_al_dia', models.BooleanField(default=False, verbose_name='Vacunas al Día')),
                ('vacunas_observaciones', models.TextField(blank=True, null=True, verbose_name='Obs. Vacunas')),
                ('examenes_solicitados', models.TextField(blank=True, null=True, verbose_name='Exámenes Solicitados')),
                ('examenes_resultados', models.TextField(blank=True, null=True, verbose_name='Resultados Exámenes')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('indicaciones', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('proxima_control', models.DateField(blank=True, null=True, verbose_name='Próximo Control')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('historial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulario_fuv', to='historial.historialpaciente', verbose_name='Historial Asociado')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_fuv', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_fuv', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Formulario FUV',
                'verbose_name_plural': 'Formularios FUV',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
