# Generated by Django 5.2.11 on 2026-02-27 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_numero', models.CharField(help_text='Sin puntos ni guión. Ej: 12345678', max_length=8, validators=[django.core.validators.RegexValidator(message='El RUN debe tener entre 1 y 8 dígitos (sin puntos).', regex='^\\d{1,8}$')], verbose_name='RUN (número)')),
                ('run_dv', models.CharField(help_text='0-9 o K', max_length=1, validators=[django.core.validators.RegexValidator(message='El dígito verificador debe ser 0-9 o K.', regex='^[0-9Kk]{1}$')], verbose_name='DV')),
                ('nombres_apellidos', models.CharField(max_length=200, verbose_name='Nombres y Apellidos')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiere no decir')], max_length=1, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('edad_anios_meses', models.CharField(blank=True, help_text='Ej: 3 años 2 meses / 3a 2m', max_length=50, null=True, verbose_name='Edad (en años y meses)')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('lengua_familia_origen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lengua familia de origen')),
                ('lengua_habitual', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lengua que usa habitualmente')),
                ('fecha_reevaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Reevaluación')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Peso (kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IMC')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('indicaciones', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Evaluación de Salud',
                'verbose_name_plural': 'Evaluaciones de Salud',
                'indexes': [models.Index(fields=['run_numero', 'run_dv'], name='formulario__run_num_075e64_idx'), models.Index(fields=['fecha_nacimiento'], name='formulario__fecha_n_144149_idx'), models.Index(fields=['fecha_reevaluacion'], name='formulario__fecha_r_540f63_idx')],
            },
        ),
    ]
