# Generated by Django 5.2.11 on 2026-02-27 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_numero', models.CharField(help_text='Sin puntos ni guión. Ej: 12345678', max_length=8, validators=[django.core.validators.RegexValidator(message='El RUT debe tener entre 1 y 8 dígitos (sin puntos).', regex='^\\d{1,8}$')], verbose_name='RUT (número)')),
                ('rut_dv', models.CharField(help_text='0-9 o K', max_length=1, validators=[django.core.validators.RegexValidator(message='El dígito verificador debe ser 0-9 o K.', regex='^[0-9Kk]{1}$')], verbose_name='DV')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo_llegada', models.CharField(blank=True, choices=[('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('DERIVACION', 'Derivación'), ('PRIMERA_VEZ', 'Primera vez'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='Tipo Llegada')),
                ('etapa', models.CharField(blank=True, choices=[('INGRESO', 'Ingreso'), ('EVALUACION', 'Evaluación'), ('TRATAMIENTO', 'Tratamiento'), ('ALTA', 'Alta'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='Etapa')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Edad')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Peso (Kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Talla (cm)')),
                ('cc_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='C.C. (cm)')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Anamnesis')),
                ('examen_fisico', models.TextField(blank=True, null=True, verbose_name='Examen Físico')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('control', models.TextField(blank=True, null=True, verbose_name='Control')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Llegada',
                'verbose_name_plural': 'Llegadas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['rut_numero', 'rut_dv'], name='llegadas_ll_rut_num_24be1f_idx'), models.Index(fields=['fecha'], name='llegadas_ll_fecha_6dee44_idx'), models.Index(fields=['nombre'], name='llegadas_ll_nombre_d4d11e_idx')],
            },
        ),
    ]
