# Generated by Django 5.2.11 on 2026-02-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Llegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Llegada')),
                ('hora_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Atención')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('estado', models.CharField(choices=[('ESPERANDO', 'Esperando'), ('EN_ATENCION', 'En Atención'), ('ATENDIDO', 'Atendido')], default='ESPERANDO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llegadas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='llegada', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Llegada',
                'verbose_name_plural': 'Llegadas',
                'ordering': ['-hora_llegada'],
            },
        ),
    ]
