# Generated by Django 5.2.11 on 2026-02-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llegadas', '0001_nuevo_modelo_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llegada',
            name='tipo_llegada',
            field=models.CharField(blank=True, choices=[('CONTROL', 'Control'), ('ENFERMEDAD', 'Enfermedad'), ('CONTROL_ENFERMEDAD', 'Control de Enfermedad')], max_length=30, null=True, verbose_name='Tipo Llegada'),
        ),
    ]
