# Generated by Django 5.2.11 on 2026-02-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de Consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Anamnesis')),
                ('examen_fisico', models.TextField(blank=True, null=True, verbose_name='Examen Físico')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('indicaciones', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('receta', models.TextField(blank=True, null=True, verbose_name='Receta/Medicamentos')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frec. Cardíaca (lpm)')),
                ('saturacion_oxigeno', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saturación O₂ (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='pacientes.paciente', verbose_name='Paciente')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='reservas.reserva', verbose_name='Reserva Asociada')),
            ],
            options={
                'verbose_name': 'Historial del Paciente',
                'verbose_name_plural': 'Historial de Pacientes',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
