# Generated by Django 5.2.11 on 2026-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_consulta',
            field=models.CharField(choices=[('CONTROL', 'Control'), ('ENFERMEDAD', 'Enfermedad'), ('CONTROL_ENFERMEDAD', 'Control de Enfermedad')], default='CONTROL', max_length=20, verbose_name='Tipo de Consulta'),
        ),
    ]
